### ISSUE TITLE
log-cache-scheduler would not start on recreate

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/log-cache-release#21]
We recreated the scheduler VMs and failed to start the log-cache-scheduler with repeated failures of the following ...

```
2019/03/12 13:41:54.755751 Starting Log Cache Scheduler...
FIELD NAME:                    TYPE:          ENV:                      REQUIRED:  VALUE:
Config.HealthAddr              string         HEALTH_ADDR               false      localhost:6064
Config.Interval                time.Duration  INTERVAL                  false      15s
Config.Count                   int            COUNT                     false      100
Config.ReplicationFactor       int            REPLICATION_FACTOR        false      1
Config.NodeAddrs               []string       NODE_ADDRS                false      [14430b85-6375-4d7a-84ee-8459919a499d.doppler.default.yz-stage0.microbosh:8080 187d7f9c-8c09-4d6b-b23b-f7e3c1e8193a.doppler.default.yz-stage0.microbosh:8080 72a066d8-634e-4ffe-a758-6d9e05857534.doppler.default.yz-stage0.microbosh:8080 77aaee4d-7d84-45ba-a000-6e829d9058c3.doppler.default.yz-stage0.microbosh:8080 bd8cb129-a554-4d76-9a48-3f3108e8db84.doppler.default.yz-stage0.microbosh:8080 cd556ff2-111b-464f-ba26-73c3f560fcff.doppler.default.yz-stage0.microbosh:8080 d74c45fe-9fd9-4578-9727-bf2dcd76618c.doppler.default.yz-stage0.microbosh:8080 e56ca6ec-f875-4026-b11b-7bd375623668.doppler.default.yz-stage0.microbosh:8080]
Config.LeaderElectionEndpoint  string         LEADER_ELECTION_ENDPOINT  false
TLS.CAPath                     string         CA_PATH                   true       /var/vcap/jobs/log-cache-scheduler/config/certs/ca.crt
TLS.CertPath                   string         CERT_PATH                 true       /var/vcap/jobs/log-cache-scheduler/config/certs/log_cache.crt
TLS.KeyPath                    string         KEY_PATH                  true       /var/vcap/jobs/log-cache-scheduler/config/certs/log_cache.key
panic: runtime error: index out of range

goroutine 14 [running]:
code.cloudfoundry.org/go-orchestrator.(*Orchestrator).rebalance(0xc00010e500, 0xc0004405a0, 0xc000440570, 0xc0001981b0, 0xc000394280, 0x8)
    /var/vcap/packages/log-cache-scheduler/src/code.cloudfoundry.org/go-orchestrator/orchestrator.go:192 +0x4d0
code.cloudfoundry.org/go-orchestrator.(*Orchestrator).NextTerm(0xc00010e500, 0x988f60, 0xc00002a038)
    /var/vcap/packages/log-cache-scheduler/src/code.cloudfoundry.org/go-orchestrator/orchestrator.go:133 +0x160
code.cloudfoundry.org/log-cache/internal/scheduler.(*Scheduler).Start.func1(0xc00010e480)
    /var/vcap/packages/log-cache-scheduler/src/code.cloudfoundry.org/log-cache/internal/scheduler/scheduler.go:178 +0xd1
created by code.cloudfoundry.org/log-cache/internal/scheduler.(*Scheduler).Start
    /var/vcap/packages/log-cache-scheduler/src/code.cloudfoundry.org/log-cache/internal/scheduler/scheduler.go:172 +0x2e9
```

Finally resolved this by manually doing a restart of all the log-cache jobs on the dopplers.   

This is on log-cache 2.0.2

**Comment by toddboom** [comment]
@andrew-edgar Thanks for reporting this. Is this the first time you've seen this?

We think it might be something to do with the `NODE_ADDRS` array being out of sync with the actual addresses of the log cache nodes. Had you done any other re-deployments of the doppler VMs before this happened?

**Comment by johannaratliff** [comment]
He mentioned that he [checked that all the IPs resolved](https://cloudfoundry.slack.com/archives/CBFB7NP9B/p1552402473003100) to correct doppler addrs. I think we can just add a error log somewhere we are `log.Fatal`ing.

**Comment by jtuchscherer** [comment]
@andrew-edgar we are about to release log-cache v1.4.8 with a fix for this and we will port this to the 2.0.x and 2.1.x line pretty soon.

**Comment by andrew-edgar** [comment]
That's cool thanks.

**Comment by jtuchscherer** [comment]
The release are now cut. Please let us know and reopen this issue if the problem reoccurs after the fix.

Thanks for reporting this.
